//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_test
    {
        public int user_id { get; set; }
        public int test_id { get; set; }
        public int result { get; set; }
        public System.TimeSpan time { get; set; }
        public int scores { get; set; }
        public System.DateTime date_started { get; set; }
        public System.DateTime date_finished { get; set; }
    
        public virtual test test { get; set; }
        public virtual user user { get; set; }
    }
}
